name: medica
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  font_awesome_flutter: ^10.3.0
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  otp_text_field: ^1.1.3
  pinput: ^2.2.23
  local_auth: ^2.1.3
  local_auth_android: ^1.0.18
  fluttertoast: ^8.1.3
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  google_sign_in: ^6.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
