// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJE71OZw5yanctKwO77G1YfZM9j9dnGaQ',
    appId: '1:1069480650643:web:cffd9ae5d81afcfd2aea66',
    messagingSenderId: '1069480650643',
    projectId: 'medica-9ee3f',
    authDomain: 'medica-9ee3f.firebaseapp.com',
    storageBucket: 'medica-9ee3f.appspot.com',
    measurementId: 'G-BMMGCS1GSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLe8XidIw0ide8m_uQwz8e1V3O4zcEcWw',
    appId: '1:1069480650643:android:91779807ed41df042aea66',
    messagingSenderId: '1069480650643',
    projectId: 'medica-9ee3f',
    storageBucket: 'medica-9ee3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd06oLQZaK3OkB4V345LR-wIFm44-nNKk',
    appId: '1:1069480650643:ios:a0d9891d5d5647e92aea66',
    messagingSenderId: '1069480650643',
    projectId: 'medica-9ee3f',
    storageBucket: 'medica-9ee3f.appspot.com',
    iosClientId: '1069480650643-o9cfbc3oq50nmgjtosn01rafpjutmvj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.medica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd06oLQZaK3OkB4V345LR-wIFm44-nNKk',
    appId: '1:1069480650643:ios:a0d9891d5d5647e92aea66',
    messagingSenderId: '1069480650643',
    projectId: 'medica-9ee3f',
    storageBucket: 'medica-9ee3f.appspot.com',
    iosClientId: '1069480650643-o9cfbc3oq50nmgjtosn01rafpjutmvj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.medica',
  );
}
